# Generated by Django 4.2 on 2023-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_est_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('precio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('ancho', models.CharField(max_length=100)),
                ('largo', models.CharField(max_length=100)),
            ],
        ),
    ]
