# Generated by Django 4.2 on 2023-11-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_est_app', '0002_estacionamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
    ]
