# Generated by Django 4.2 on 2023-11-20 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_est_app', '0003_delete_estacionamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstArrendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_est_app.enarriendo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
